import { useState, useEffect } from 'react';
import { Link } from '@tanstack/react-router';
import { apiClient } from '../api/client';
import { StatusBadge } from '../components/shared/StatusBadge';
import { Spinner } from '../components/shared/Spinner';
import { OPERATION_LABELS } from '../types';
import type { ReportSummary } from '../types';

/**
 * ReportsPage — /reports
 *
 * Displays the history of all reports generated by the user's tasks.
 * Each row links to /reports/:id for the full detail view.
 *
 * The list is fetched once on mount from GET /reports.
 * Reports are sorted by generation date descending (newest first).
 */
export function ReportsPage() {
  const [reports, setReports] = useState<ReportSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    async function fetch_reports() {
      try {
        const response = await apiClient.get<ReportSummary[]>('/reports');
        // Sort newest first.
        const sorted = [...response.data].sort(
          (a, b) => new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime(),
        );
        setReports(sorted);
      } catch {
        setError('Impossibile caricare i report. Riprova più tardi.');
      } finally {
        setLoading(false);
      }
    }
    fetch_reports();
  }, []);

  // ---- Render ----

  if (loading) {
    return (
      <div className="flex items-center gap-2 text-sm text-gray-500">
        <Spinner size="sm" />
        Caricamento report…
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl">
      <h1 className="mb-1 text-lg font-semibold text-[#2a2a2a]">Storico Report</h1>
      <p className="mb-6 text-sm text-gray-400">
        Tutti i report generati dalle operazioni completate.
      </p>

      {error && (
        <div className="mb-4 rounded border border-red-200 bg-red-50 px-3 py-2 text-sm text-[#cc2222]">
          {error}
        </div>
      )}

      {reports.length === 0 && !error ? (
        <div className="rounded-lg border border-dashed border-[#cccccc] p-10 text-center text-sm text-gray-400">
          Nessun report disponibile.{' '}
          <Link to="/run" className="text-[#2277cc] hover:underline">
            Avvia un'operazione
          </Link>{' '}
          per generarne uno.
        </div>
      ) : (
        <div className="overflow-hidden rounded-lg border border-[#cccccc]">
          <table className="w-full text-sm">
            <thead className="bg-white text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
              <tr>
                <th className="px-4 py-3">Operazione</th>
                <th className="px-4 py-3">Stato</th>
                <th className="px-4 py-3">Data</th>
                <th className="px-4 py-3">Durata</th>
                <th className="px-4 py-3"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#eeeeee] bg-white">
              {reports.map((report) => (
                <tr key={report.id} className="hover:bg-gray-50 transition">
                  <td className="px-4 py-3">
                    {/* Title is assigned by the backend; operation is shown as a secondary label */}
                    <p className="font-medium text-[#2a2a2a]">{report.title}</p>
                    <p className="text-xs text-gray-400 mt-0.5">
                      {OPERATION_LABELS[report.operation] ?? report.operation}
                    </p>
                  </td>
                  <td className="px-4 py-3">
                    <StatusBadge status={report.status} />
                  </td>
                  <td className="px-4 py-3 text-gray-500 text-xs">
                    {new Date(report.generatedAt).toLocaleString('it-IT', {
                      day: '2-digit',
                      month: '2-digit',
                      year: 'numeric',
                      hour: '2-digit',
                      minute: '2-digit',
                    })}
                  </td>
                  <td className="px-4 py-3 text-gray-500 text-xs">
                    {report.durationMs
                      ? `${(report.durationMs / 1000).toFixed(1)}s`
                      : '—'}
                  </td>
                  <td className="px-4 py-3 text-right">
                    <Link
                      to="/reports/$id"
                      params={{ id: report.id }}
                      className="text-xs font-medium text-[#2277cc] hover:underline"
                    >
                      Visualizza →
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
